

class DataIngestionartifact:...
class DataValidationartifacts:...
class DataTransformationartifacts:...
class ModelTrainerartifacts:...
class ModelEvaluationarticats:...
class ModelPusherartifacts:...